var data = {
  images: [
  {
    src: ["https://pbs.twimg.com/media/GYMSUGbakAAQYGB?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GYMSUGbakAAQYGB?format=jpg&name=medium",
    title: "Floofy Seren",
    artist: "Cosme",
    artist_url: "https://x.com/rthunderatk",
    art_url: "https://x.com/Mina_776_/status/1838333215284867392",
    desc: "",
    date_str: "September 24, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GUyVOp-XEAErm75?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GUyVOp-XEAErm75?format=jpg&name=medium",
    title: "Luna Moths",
    artist: "Aster",
    artist_url: "https://x.com/ZefirArt",
    art_url: "https://x.com/ZefirArt/status/1822996629751738386",
    desc: "Gift from @Catnipium",
    date_str: "August 12, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GVWDZScaoAE7XI9?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GVWDZScaoAE7XI9?format=jpg&name=medium",
    title: "Seren and Anthea",
    artist: "Yuru Socks",
    artist_url: "https://x.com/yuru_socks",
    art_url: "https://x.com/yuru_socks/status/1825509700500345047",
    desc: "Gift from @Galaxy__Angel",
    date_str: "August 19, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GX4V52YWIAA0Hkx?format=jpg&name=900x900", "https://pbs.twimg.com/media/GV_x6w4bEAAKix6?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GX4V52YWIAA0Hkx?format=jpg&name=900x900",
    title: "Pokemon collab",
    artist: "Chika_nyanco",
    artist_url: "https://x.com/chika_nyanco",
    art_url: "https://x.com/Swordsmaster5/status/1828446224309203317",
    desc: "",
    date_str: "August 27, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GW9jdODboAAFK4e?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GW9jdODboAAFK4e?format=jpg&name=medium",
    title: "Seren and Keeva",
    artist: "Moccha Kofii",
    artist_url: "https://x.com/moccha_kofii",
    art_url: "https://x.com/Mina_776_/status/1832792929389134194",
    desc: "Collab with @Swordmaster5",
    date_str: "September 8, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GVN0G3NbwAEJu5H?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GVN0G3NbwAEJu5H?format=jpg&name=medium",
    title: "Seren 4",
    artist: "Manjuu",
    artist_url: "https://x.com/Manjuu_18banme",
    art_url: "https://x.com/Manjuu_18banme/status/1824944299223728466",
    desc: "",
    date_str: "August 17, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GTlzHpgXEAA3-wH?format=jpg&name=large", "https://pbs.twimg.com/media/GTlzHpeW0AAaTwb?format=jpg&name=large"],
    thumbnail: "https://pbs.twimg.com/media/GTlzHpgXEAA3-wH?format=jpg&name=large",
    title: "Lugh & Seren",
    artist: "Sirotsumesou",
    artist_url: "https://x.com/sirotsumesou_7",
    art_url: "https://x.com/PEve862/status/1817613614792012227",
    desc: "Gift from @PEve862",
    date_str: "July 28, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/nBp2lso.gif"],
    thumbnail: "https://i.imgur.com/nBp2lso.gif",
    title: "Seren 3",
    artist: "9pokamo",
    artist_url: "https://x.com/9pokamo",
    art_url: "",
    desc: "",
    date_str: "August 7, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/JTccIdj.png"],
    thumbnail: "https://i.imgur.com/JTccIdj.png",
    title: "Seren 2",
    artist: "Retort Musica",
    artist_url: "https://x.com/retort_musica",
    art_url: "https://x.com/Mina_776_/status/1817974463205622152",
    desc: "",
    date_str: "July 29, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GTQRlpXaYAESazS?format=jpg&name=900x900"],
    thumbnail: "https://pbs.twimg.com/media/GTQRlpXaYAESazS?format=jpg&name=900x900",
    title: "Adult Seren",
    artist: "Mina",
    artist_url: "https://x.com/Mina_776_",
    art_url: "https://x.com/Mina_776_/status/1816095889687245264",
    desc: "Gen3 Ensemble bonus illustration.",
    date_str: "July 24, 2024",
    tags: ["oc"],
    hidden: false
  },
  {
    src: ["https://i.redd.it/6sgv0lp3hcpc1.jpeg"],
    thumbnail: "https://i.redd.it/6sgv0lp3hcpc1.jpeg",
    title: "Mareeta & Ced",
    artist: "Moccha Kofii",
    artist_url: "https://twitter.com/moccha_kofii",
    art_url: "https://x.com/moccha_kofii/status/1770137632112001409?s=20",
    desc: "",
    date_str: "March 19, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GN_l1QCWEAAwLt_?format=jpg&name=large"],
    thumbnail: "https://pbs.twimg.com/media/GN_l1QCWEAAwLt_?format=jpg&name=large",
    title: "Rally for Gaza 4",
    artist: "Ciarre",
    artist_url: "https://x.com/ciarre_",
    art_url: "https://x.com/ciarre_/status/1792616278244430239",
    desc: "Reward for donating to the Palestine Children's Relief Fund.",
    date_str: "May 20, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/VKtQc1Z.jpeg"],
    thumbnail: "https://i.imgur.com/VKtQc1Z.jpeg",
    title: "Sword Lilies",
    artist: "tsunrugi",
    artist_url: "https://twitter.com/tsunrugi",
    art_url: "https://twitter.com/Mina_776_/status/1721207011273245082",
    desc: "The flowers in this piece are gladiloi, also known as Sword Lilies. They represent strength of character, faithfulness, moral integrity, and remembrance.",
    date_str: "November 5, 2023",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/WrKKK3z.jpeg"],
    thumbnail: "https://i.imgur.com/WrKKK3z.jpeg",
    title: "Garden Bench",
    artist: "Nico",
    artist_url: "https://twitter.com/Nico_squitter",
    art_url: "https://twitter.com/Mina_776_/status/1726108770101833963/photo/1",
    desc: "Birthday gift from @MisoSoup247",
    date_str: "January 16, 2022",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/B1JNJxG.png"],
    thumbnail: "https://i.imgur.com/B1JNJxG.png",
    title: "Snow Feh",
    artist: "Shugo",
    artist_url: "https://twitter.com/hiomaika",
    art_url: "https://x.com/hiomaika/status/1708829194023813528?s=20",
    desc: "Funded by the 3rd annual CYL Prediction Contest.",
    date_str: "November 25, 2023",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/jENQGj6.png"],
    thumbnail: "https://i.imgur.com/jENQGj6.png",
    title: "Eyvel & Mareeta",
    artist: "BugLewdy",
    artist_url: "https://twitter.com/BugLewdy",
    art_url: "https://x.com/BugLewdy/status/1747415939992445194?s=20",
    desc: "Birthday gift from @MrTalkingDinosaur",
    date_str: "January 16, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/TkdNzyE.jpeg"],
    thumbnail: "https://i.imgur.com/TkdNzyE.jpeg",
    title: "Skeb",
    artist: "Nagi",
    artist_url: "https://twitter.com/nagi_mutou",
    art_url: "https://twitter.com/nagi_mutou/status/1748001048009306623",
    desc: "",
    date_str: "January 18, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.redd.it/5gsvhgm9gqoc1.png"],
    thumbnail: "https://i.redd.it/5gsvhgm9gqoc1.png",
    title: "Rally for Gaza 1",
    artist: "DaphneComics",
    artist_url: "https://twitter.com/DaphneComics",
    art_url: "https://twitter.com/Mina_776_/status/1768834297396629652",
    desc: "Reward for participating in the Rally for Gaza fundraiser event.",
    date_str: "March 15, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GKzqEtDboAAMfkV?format=jpg&name=large"],
    thumbnail: "https://pbs.twimg.com/media/GKzqEtDboAAMfkV?format=jpg&name=large",
    title: "Rally for Gaza 2",
    artist: "zoedapoey",
    artist_url: "https://twitter.com/zoedapoey",
    art_url: "https://x.com/Mina_776_/status/1778053322311913568",
    desc: "Reward for donating to the Palestine Children's Relief Fund.",
    date_str: "April 10, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GMB0oftaQAAqf8y?format=jpg&name=large"],
    thumbnail: "https://pbs.twimg.com/media/GMB0oftaQAAqf8y?format=jpg&name=large",
    title: "Rally for Gaza 3",
    artist: "Izu",
    artist_url: "https://twitter.com/izusibiki",
    art_url: "https://x.com/Mina_776_/status/1783553693771850021",
    desc: "Reward for donating to the Palestine Children's Relief Fund.",
    date_str: "April 25, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/mZUJoNJ.png"],
    thumbnail: "https://i.imgur.com/mZUJoNJ.png",
    title: "Seren (OC)",
    artist: "Anne",
    artist_url: "https://twitter.com/uneasywolf",
    art_url: null,
    desc: "Gift from @MrTalkingDinosaur",
    date_str: "March 31, 2024",
    tags: [],
    hidden: false
  },
  {
    src: ["https://i.imgur.com/tByQnjx.png"],
    thumbnail: "https://i.imgur.com/tByQnjx.png",
    title: "Winter Mareeta",
    artist: "Yunii",
    artist_url: "https://twitter.com/yuniyuniii3",
    art_url: "https://twitter.com/Mina_776_/status/1732461250838491302",
    desc: "",
    date_str: "December 6, 2023",
    tags: [],
    hidden: false
  },
  {
    src: ["https://pbs.twimg.com/media/GM0Ok8qbcAAYRym?format=jpg&name=medium"],
    thumbnail: "https://pbs.twimg.com/media/GM0Ok8qbcAAYRym?format=jpg&name=medium",
    title: "Seren & Lugh",
    artist: "Mina",
    artist_url: null,
    art_url: "https://twitter.com/Mina_776_/status/1787100656811270313/",
    desc: "For @PEve862",
    date_str: "May 5, 2025",
    tags: ["oc"],
    hidden: false
  }]
};